version: "3"

services:
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.0
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-cluster
      - cluster.initial_master_nodes=es00,es01,es02
      - discovery.seed_hosts=es00,es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.master=true
      - node.data=true
      - node.ingest=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    ports:
      - 9203:9200
    networks:
      - elastic
  es04:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.0
    container_name: es04
    environment:
      - node.name=es04
      - cluster.name=es-cluster
      - cluster.initial_master_nodes=es00,es01,es02
      - discovery.seed_hosts=es00,es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.master=true
      - node.data=true
      - node.ingest=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data04:/usr/share/elasticsearch/data
    ports:
      - 9204:9200
    networks:
      - elastic
  es05:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.0
    container_name: es05
    environment:
      - node.name=es05
      - cluster.name=es-cluster
      - cluster.initial_master_nodes=es00,es01,es02
      - discovery.seed_hosts=es00,es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.master=true
      - node.data=true
      - node.ingest=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data05:/usr/share/elasticsearch/data
    ports:
      - 9205:9200
    networks:
      - elastic

volumes:
  data03:
    driver: local
  data04:
    driver: local
  data05:
    driver: local

networks:
  elastic:
    external: true
