version: "3"

services:
  es06:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.0
    container_name: es06
    environment:
      - node.name=es06
      - cluster.name=es-cluster
      - discovery.seed_hosts=es00,es01,es02,es03,es04,es05
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.master=true
      - node.data=true
      - node.ingest=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data06:/usr/share/elasticsearch/data
    ports:
      - 9206:9200
    networks:
      - elastic

volumes:
  data06:
    driver: local

networks:
  elastic:
    external: true
